package com.hr.hrserver.controller;

import com.hr.hrserver.dao.EmployeeDaoImpl;
import com.hr.hrserver.dao.UserDaoImpl;
import com.hr.hrserver.model.FacilityReportAndUsername;
import com.hr.hrserver.pojo.FacilityReportDetail;
import com.hr.hrserver.pojo.HouseDetail;
import com.hr.hrserver.service.HousingAndFacilityReportService;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

@RestController
@CrossOrigin
public class HousingController {

    private final HousingAndFacilityReportService HAFRS = new HousingAndFacilityReportService();

    @RequestMapping("/houseDetail")
    @ResponseBody
    public HouseDetail fetchHouseDetailByUserName(String username){
        UserDaoImpl userDao = new UserDaoImpl();
        EmployeeDaoImpl employeeDao = new EmployeeDaoImpl();
        int eid = employeeDao.getEmployeeByUserId(
                userDao.findIdbyNmae(username)
        ).getID();
        return HAFRS.getHouseDetailByEmployeeID(eid);
    }

    @RequestMapping("/facilityReport")
    @ResponseBody
    //username -> employeeId -> houseID -> all employee id that has this houseID
    // -> all facilityReport Generated by these employees
    public List<FacilityReportAndUsername> fetchFacilityReportByUserName(String username){
        return HAFRS.getFacilityReportByUsername(username);
    }

    @RequestMapping("/facilityReportDetail")
    @ResponseBody
    public List<FacilityReportDetail> fetchFacilityReportDetailByFacilityReportID(int id){
        return
                HAFRS.getFacilityReportDetailByFacilityReportID(id);
    }

    @RequestMapping("/facilityReportAddComment")
    @ResponseBody
    //return the comment id
    public int addCommentToReport(int reportID, String username, String comment){

        Map<Object, Object> data = new HashMap<Object, Object>();
        data.put("reportID",reportID);
        data.put("username",username);
        data.put("comment",comment);

        return HAFRS.addNewCommentToReport(data);
    }

    @RequestMapping("/facilityAddReport")
    @ResponseBody
    //return id of the added report
    public int addReport(String username, String description, String title){
        Map<Object, Object> data = new HashMap<Object, Object>();
        data.put("title",title);
        data.put("username",username);
        data.put("description",description);
        return HAFRS.addNewReport(data);
    }

    @RequestMapping("/facilityEditComment")
    @ResponseBody
    public String editComment(int reportDetailID, String newComment){
        return
                HAFRS.saveOrUpdateComment(reportDetailID, newComment);
    }

    @RequestMapping("/facilityEditReport")
    @ResponseBody
    public String editReport(int reportID, String newDescription, boolean changeStatus){
        return
                HAFRS.saveOrUpdateReport(reportID,newDescription,changeStatus);
    }

}
