package com.hr.hrserver.controller;

import com.hr.hrserver.dao.EmployeeDaoImpl;
import com.hr.hrserver.dao.UserDaoImpl;
import com.hr.hrserver.model.FacilityReportAndUsername;
import com.hr.hrserver.pojo.FacilityReport;
import com.hr.hrserver.pojo.FacilityReportDetail;
import com.hr.hrserver.pojo.HouseDetail;
import com.hr.hrserver.service.HousingAndFacilityReportService;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

@RestController
@CrossOrigin
public class HousingController {

    @RequestMapping("/houseDetail")
    @ResponseBody
    public HouseDetail fetchHouseDetailByUserName(String username){
        UserDaoImpl userDao = new UserDaoImpl();
        EmployeeDaoImpl employeeDao = new EmployeeDaoImpl();
        int eid = employeeDao.getEmployeeByUserId(
                userDao.findIdbyNmae(username)
        ).getID();
        HousingAndFacilityReportService HaFRS = new HousingAndFacilityReportService();
        return HaFRS.getHouseDetailByEmployeeID(eid);
    }

    @RequestMapping("/facilityReport")
    @ResponseBody
    //username -> employeeId -> houseID -> all employee id that has this houseID
    // -> all facilityReport Generated by these employees
    public List<FacilityReportAndUsername> fetchFacilityReportByUserName(String username){
        HousingAndFacilityReportService HaFRS = new HousingAndFacilityReportService();
        return HaFRS.getFacilityReportByUsername(username);
    }

    @RequestMapping("/facilityReportDetail")
    @ResponseBody
    public List<FacilityReportDetail> fetchFacilityReportDetailByFacilityReportID(int id){
        HousingAndFacilityReportService HaFRS = new HousingAndFacilityReportService();
        return
                HaFRS.getFacilityReportDetailByFacilityReportID(id);
    }

    @RequestMapping("/facilityReportAddComment")
    @ResponseBody
    //return the comment id
    public int addCommentToReport(int reportID, String username, String comment){

        Map<Object, Object> data = new HashMap<Object, Object>();
        data.put("reportID",reportID);
        data.put("username",username);
        data.put("comment",comment);
        HousingAndFacilityReportService hafrs = new HousingAndFacilityReportService();

        return hafrs.addNewCommentToReport(data);
    }

    @RequestMapping("/facilityAddReport")
    @ResponseBody
    //return id of the added report
    public int addReport(String username, String Description){
        Map<Object, Object> data = new HashMap<Object, Object>();

        return -1;
    }

    @RequestMapping("/facilityEditComment")
    @ResponseBody
    public void editComment(int reportDetailID, String newComment){
    }

    @RequestMapping("/facilityEditReport")
    @ResponseBody
    public void editReport(int reportID, String newDescription){
    }


}
